dbt_transforms:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-warehouse
      user: postgres
      password: password
      port: 5432
      dbname: ml_workout
      schema: dbt_ml_workout
      threads: 1