version: 2

models:
    - name: dbt_ml_workout
      description: "Tags for all projects"
      columns:
          - name: id
            description: "Unique ID."
            tests:
                - unique
                - not_null
          - name: image
            description: "Image url."
            tests:
              - unique
                - not_null
          - name: choice
            description: "Labeled tag for the project."
            tests:
                - not_null