version: "3.7"

services:
  warehouse:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ml_workout
      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: postgres-warehouse
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=warehouse
    container_name: adminer
    ports:
      - 8082:8080
    depends_on:
      - warehouse

volumes:
  pgdata:
    
