version: "3.7"

services:
  sftp:
    # https://hub.docker.com/r/atmoz/sftp
    image: atmoz/sftp
    container_name: SFTP
    ports:
      - 22:22
    # volumes:
    #   - data:/home/usr/upload
    command: usr:pass:::upload
    
volumes:
  data: