version: "3.7"

services:
  sftp:
    # https://hub.docker.com/r/atmoz/sftp
    image: atmoz/sftp
    ports:
      - 22:22
    volumes:
      - ../data_lake/files/sftp_upload:/home/usr/upload
    command: usr:pass
    
